name: Recovery pack

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC+3 date +%s )" >> $GITHUB_OUTPUT
    - name: Prepare the environment
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install aria2 gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib libc6-dev lib32ncurses5-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libwxgtk3.0-gtk3-dev libxml2 lzop pngcrush schedtool squashfs-tools imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses5 python3
    - name: Install OpenJDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'  
    - name: Install repo
      run: |
        mkdir out
        aria2c -j$(nproc --all) https://github.com/reocat/mirror/releases/download/20240628/signed-ota_update.zip
        aria2c -j$(nproc --all) https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
        tar -xzvf payload-du*
        chmod +x payload-dumper-go
        ./payload-dumper-go -p boot,dtbo,vendor_boot,vendor_dlkm,system_dlkm signed-ota_update.zip >> /dev/null
        cd extr*
        mv boot.img ../out
        mv dtbo.img ../out
        mv vendor_boot.img ../out
        mv vendor_dlkm.img ../out
        mv system_dlkm.img ../out =
        cd ..
        zip -r recovery.zip out/
    - name: Upload kernel
      uses: actions/upload-artifact@v4
      with:
        name: recovery-${{ steps.get_time.outputs.TIME }}
        path: "out/*"

    - name: Release build
      uses: Ofceab-Studio/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: "Kernel is built!"
        document: recovery.zip
